/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: '#f5f5f5',
        foreground: '#0f0f0f',
        card: '#ffffff',
        'card-foreground': '#0f0f0f',
        popover: '#ffffff',
        'popover-foreground': '#0f0f0f',
        primary: '#b81969',
        'primary-foreground': '#ffffff',
        secondary: '#f6c0db',
        'secondary-foreground': '#4a0929',
        muted: '#f9fafb',
        'muted-foreground': '#475467',
        accent: '#f6c0db',
        'accent-foreground': '#4a0929',
        destructive: '#E84545',
        'destructive-foreground': '#ffffff',
        border: '#E2E8F0',
        input: 'transparent',
        'input-background': '#FAFBFC',
        'switch-background': '#CBD5E1',
        ring: '#b81969',
        wine: '#4a0929',
        'wine-light': '#6b1240',
        'wine-border': '#901452',
        pink: '#b81969',
        'pink-light': '#f6c0db',
        yellow: '#f9f804',
      },
      borderRadius: {
        lg: '0.75rem',
        md: 'calc(0.75rem - 2px)',
        sm: 'calc(0.75rem - 4px)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
